Nar 405 occupation filtering
JobtechSwe/sokannonser-api pull request #110
Opened 2020-10-05 09:08 UTC by oskardrenske-ith

2020-10-05 09:16 UTC, halge reviewed
ok

2020-10-05 09:19 UTC, halge requested changes
unit tests

2020-10-05 10:12 UTC, halge reviewed
ok.

2020-10-05 12:42 UTC, oskardrenske-ith commented on sokannonser/repository/taxonomy.py
> +    # TODO Included preferred_label for logging issues. Remove if unnecessary...
are the Todos in this file still relevant?

2020-10-05 12:52 UTC, oskardrenske-ith commented on sokannonser/repository/querybuilder.py
> +    def _build_yrkessamlingar_query(self, yrkessamlingar=[]):
why have a default value? It will be caught by the "if not" check

2020-10-06 06:43 UTC, lerca commented on sokannonser/repository/taxonomy.py
> +    # TODO Included preferred_label for logging issues. Remove if unnecessary...
Agree, have removed!

2020-10-06 06:44 UTC, lerca commented on sokannonser/repository/querybuilder.py
> +    def _build_yrkessamlingar_query(self, yrkessamlingar=[]):
Agree, have removed!

2020-10-06 08:29 UTC, lina1101 reviewed
For a request, three 'for' loops are not nice. I think we should avoid this, you can only use one 'for loop' to finish this. And I guess your code ( or functions) in 'if' and 'else' are quite similar. I guess you can improve your code.

2020-10-06 08:30 UTC, lina1101 reviewed
'[ ]' will have Key Error problem. You should use get.

2020-10-06 08:30 UTC, lina1101 reviewed
You can just concepts = response.get('data', {}).get('concepts', {})

2020-10-06 10:24 UTC, halge commented on sokannonser/repository/taxonomy.py
> +                log.error(f"Failed to fetch: {taxonomy_endpoint} after: {fail_max}, skipping. {e}")
remove all {e} before raise(e) from log.

2020-10-06 22:01 UTC, halge commented on sokannonser/repository/querybuilder.py
> +        yrken_in_yrkessamlingar_id = []
remove id from names?

2020-10-07 06:31 UTC, lerca commented on sokannonser/repository/querybuilder.py
> +        yrken_in_yrkessamlingar_id = []
The id part is from Oskars review comment, to separate the naming of it from yrkessamling

2020-10-07 07:07 UTC, halge commented on sokannonser/repository/querybuilder.py
> +        yrken_in_yrkessamlingar_id = []
do those really need id in the name?

2020-10-07 08:08 UTC, merged

2020-10-08 06:25 UTC, lerca commented
> unit tests

Fixed