Nar 733 remove la v1
JobtechSwe/sokannonser-api pull request #122
Opened 2021-01-05 09:47 UTC by oskardrenske-ith

New test ads and modified tests to match them

2021-01-07 10:37 UTC, halge requested changes

2021-01-07 10:37 UTC, halge commented on tests/api_tests/search/test_stats.py
>      params = {'stats': 'region', 'offset': 0, 'limit': 10, 'stats.limit': 5}
for stats limit can be 0.

2021-01-07 14:50 UTC, halge approved these changes

2021-01-14 12:58 UTC, lina1101 approved these changes

2021-01-15 12:35 UTC, merged