Nar 640 taxonomy replace
JobtechSwe/sokannonser-api pull request #147
Opened 2021-03-26 08:48 UTC by lina1101

2021-03-26 08:54 UTC, halge approved these changes

2021-04-01 06:40 UTC, oskardrenske-ith approved these changes

2021-04-01 06:40 UTC, oskardrenske-ith commented on sokannonser/rest/endpoint/platsannonser.py
> +        for hit in hits:
I added checks

2021-04-01 09:00 UTC, halge requested changes

2021-04-01 09:00 UTC, halge commented on sokannonser/repository/elastic_connection_with_retries.py
> +SLEEP_LENGTH = 2
add en envvar.

2021-04-01 09:00 UTC, halge commented on sokannonser/repository/elastic_connection_with_retries.py
>  ELASTIC_RETRIES = 2
add en envvar.

2021-04-01 09:00 UTC, halge commented on sokannonser/rest/endpoint/platsannonser.py
> +            occupations = hit.get('occupation', None)
is there unit tests for None and not-none? if not add #Todo

2021-04-06 08:51 UTC, halge approved these changes

2021-05-17 09:29 UTC, halge approved these changes

2021-05-17 09:48 UTC, merged