Test mode to run unit tests
JobtechSwe/sokannonser-api pull request #148
Opened 2021-04-21 05:35 UTC by oskardrenske-ith

2021-04-21 08:48 UTC, halge requested changes

2021-04-21 08:48 UTC, halge commented on sokannonser/repository/text_to_concept_methods.py
> +RE_PLUS_MINUS = re.compile(r"((^| )[+-])", re.UNICODE)
can you add a comment what does it do?

2021-04-21 08:48 UTC, halge commented on sokannonser/repository/text_to_concept.py
> +RE_PLUS_MINUS = re.compile(r"((^| )[+-])", re.UNICODE)
can you add a comment what does it do?

2021-04-21 08:48 UTC, halge commented on tests/test_resources/helper.py
> +def is_dst():
there is no dst anymore in Sweden, remove.

2021-04-21 08:48 UTC, halge commented on tests/unit_tests/test_marshal_platsannons_results_integration.py
> +    settings.TEST_MODE = True
why doubling(see up, line 24-26) ?

2021-04-21 08:48 UTC, halge commented on tests/unit_tests/test_querybuilder.py
> +    expected_time = 'now+2H/m' if is_dst() else 'now+1H/m'  # f"{expected_time}"
remove if, else

2021-04-21 08:48 UTC, halge commented on tests/unit_tests/test_querybuilder.py
> +from tests.test_resources.helper import is_dst
no need.

2021-04-21 08:48 UTC, halge commented on tests/unit_tests/test_querybuilder_experience.py
> +    expected_time = 'now+2H/m' if is_dst() else 'now+1H/m'  # f"{expected_time}"
remove if, else

2021-04-21 08:56 UTC, oskardrenske-ith commented on sokannonser/repository/text_to_concept.py
> +RE_PLUS_MINUS = re.compile(r"((^| )[+-])", re.UNICODE)
duplicated, removed

2021-04-21 09:00 UTC, oskardrenske-ith commented on tests/unit_tests/test_querybuilder_experience.py
> +    expected_time = 'now+2H/m' if is_dst() else 'now+1H/m'  # f"{expected_time}"
then it'll break in October :)

2021-04-21 09:04 UTC, oskardrenske-ith commented on tests/test_resources/helper.py
> +def is_dst():
No, that decision hasn't been made yet.

2021-04-21 09:06 UTC, oskardrenske-ith commented on tests/unit_tests/test_querybuilder.py
> +    expected_time = 'now+2H/m' if is_dst() else 'now+1H/m'  # f"{expected_time}"
No decision on DST / Normal time has been made

2021-04-21 09:11 UTC, halge approved these changes

2021-04-21 09:23 UTC, halge approved these changes

2021-04-22 15:39 UTC, lina1101 approved these changes

2021-04-22 16:33 UTC, merged