Nar 1354 tech story: Restore queryBuilder Mock for unit tests
JobtechSwe/sokannonser-api pull request #159
Opened 2021-06-29 09:41 UTC by erik-gbg

2021-06-29 10:20 UTC, oskardrenske-ith approved these changes

2021-07-01 11:06 UTC, erik-gbg commented on sokannonser/repository/__init__.py
> +         self.elastic = None
elastic is set to None when the package is imported order not to create an elastic client for the unit tests.
In the next step, when the elastic_client() function is called (from the API) the None tells us that it has not yet been created -- necessary in order to only creating it once.

2021-07-01 11:26 UTC, erik-gbg commented
Oleg,

elastic_client() is supposed to be a function. Now you have changed it to a class object. And that doesn't work at all, of course.

2021-07-01 12:50 UTC, erik-gbg commented
rebased onto develop head, to get rid of the bugs (when inspecting this branch)

2021-07-05 10:44 UTC, halge requested changes
i stop until "function" discussion is clear.

2021-07-09 08:42 UTC, closed without merging

2021-07-09 08:42 UTC, erik-gbg commented
Replaced by PR NAR-1354-the-one