develop to staging 1.18.2
JobtechSwe/sokannonser-api pull request #182
Opened 2021-09-06 13:20 UTC by oskardrenske-ith

2021-09-06 14:06 UTC, erik-gbg requested changes
In CHANGELOG:
It just says "fix bug in complete when contextual=False". But there are 4 different bug fixes:
1476, 1178, 1107, 862

2021-09-06 14:07 UTC, erik-gbg commented
Also remind me to change in Openshift configs, once it's been merged.

2021-09-07 07:36 UTC, erik-gbg approved these changes

2021-09-07 08:38 UTC, oskardrenske-ith reviewed
Approve function is not available to me since I created the PR, but I approve it this way

2021-09-07 10:38 UTC, lina1101 approved these changes

2021-09-07 10:49 UTC, merged