Dev to Staging 1.19.0
JobtechSwe/sokannonser-api pull request #194
Opened 2021-09-28 07:22 UTC by oskardrenske-ith

2021-09-28 07:36 UTC, erik-gbg approved these changes

2021-09-28 07:39 UTC, erik-gbg requested changes

2021-09-28 07:39 UTC, erik-gbg commented on CHANGELOG.md
> +
Fix changelog

2021-09-28 07:39 UTC, erik-gbg commented on common/settings.py
> +API_VERSION = '1.18.2'
Fix version

2021-09-28 08:50 UTC, lina1101 approved these changes

2021-09-28 09:31 UTC, halge requested changes
i pause until i test memcache/apikeys.

2021-09-28 14:35 UTC, erik-gbg approved these changes

2021-09-30 15:12 UTC, halge reviewed
i need to test.

2021-10-04 19:11 UTC, halge approved these changes

2021-10-04 19:12 UTC, merged